### PR TITLE
#164049745 A user should be able to edit and delete an article 

### PR DESCRIPTION
**Pull request by jomasim**
#### What does this PR do?
Implement front-end functionality for deleting and editing articles
#### Description of Task to be completed?
- [x] setup actions, reducers, sagas
- [x] implement delete article feature
- [x] implement edit article feature
- [x] write tests

1. Navigate to a folder where you would prefer to test the repository.

2. Create a directory
`mkdir myproject`

3. Navigate to the directory "myproject"
`cd myproject`

4. Clone the author's haven repository
`git clone https://github.com/andela/ah-robotics-frontend.git`

5. Change the directory into the "ah-robotics-fronted"
`cd ah-robotics-frontend`

6.  Checkout to the branch ft-articles-edit-delete-164049745
`git checkout ft-articles-edit-delete-164049745`

7. Install dependencies from the package.json
 `npm install` to install all the modules listed in the `package.json` file.
8. Setting up environment variables
 Add a **.env** file to the root folder of the project and add the configurations for social authentication in the following format, this is necessary for social login tests to pass.
           REACT_APP_API_KEY=sample_key
           REACT_APP_AUTH_DOMAIN=sample_domain
> **NOTE** : The values of the above variables are in the pinned messages section on the slack group.

9. Start the application in development mode
`npm start`
> The application opens http://localhost:3000 in the browser successfully if there are no issues.

 #### Test out the feature
The application can be accessed on heroku using the URL below : 
[https://ah-robotics-frontend-sta-pr-22.herokuapp.com/](https://ah-robotics-frontend-sta-pr-22.herokuapp.com/)

10. Register a new user by heading over to the **register** page.
11. After Registering a user, head over to the **login** page and use the details that you registered with to login
12. Click on `new article` menu to create a new article
13. After creating a new article you will be redirected to the article view page. The page provides a user with options to edit the article image as well as the article content.
14. Use the `Edit Article ` button to edit the article. 
15. Newly posted articles provide the user with an option to include an image but for existing ones, a user will have to use the image edit button on the right corner of the image.

16. To delete an article use the **Delete** button at the top right corner on the article view page. 

###  Running Tests
17. Run the following command to make sure all tests are passing:
`npm test`

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?

[#164049745](https://www.pivotaltracker.com/n/projects/2235171/stories/164049745)

### Screenshots
1.New article page
screenshot 2019-03-03 at 22 03 28
2.Article view page(**no image**)
screenshot 2019-03-03 at 22 02 49
3. Article view page(**with an image**)
screenshot 2019-03-03 at 22 00 26
4. Edit article
screenshot 2019-03-03 at 22 00 26
5. Delete article
screenshot 2019-03-03 at 22 00 01

### CODE REVIEW

**Review by Teatoller — APPROVED** [review]
Hi @jomasim,
I have tested out the feature and it is working well.

Regards
Steven Ennis

**Review by sharkdevs — COMMENTED** [review]
Good work, Consider the following:
1. Hide the image edit button if am not the owner of the article. 
screen shot 2019-03-04 at 12 15 51
2. Make the landing page image span the whole page. You can consider removing the left, right and top margins so that It covers the whole width.

@sharkdevs I have fixed that.

**Review by Paulvitalis200 — COMMENTED** [review]
Good Work @jomasim I have been able to edit and successfully delete an article I added.

**Review by johnwayodi — COMMENTED** [review]
Hey @jomasim ,
This feature is working well as expected. I have managed to test it on my machine.

**Review by waracci — COMMENTED** [review]
works as expected!

**Pull request merged**
