### PR TITLE
#162949037 Users should be able to Login to Authors Haven

### PR DESCRIPTION
**Pull request by sharkdevs**
### What does this PR do?

Creates a user Interface through which a user can be able to log in and consumes the User Login API

#### Description of Task to be completed?

- [x] Create a folder structure
- [x] Create React components
- [x] Create React Views
- [x] Design the Login User Interface
- [x] Add UI tests
- [x] Configure Redux and saga middleware
- [x] Consume the Login API
- [x] Add Component tests

### How should this be manually tested?

1. Clone this repository on your local machine using 
```
git clone https://github.com/andela/ah-robotics-frontend.git
````
2. Change your working directory to the project's directory using 
     
```
cd ah-robotics-frontend
```
3. Change to the specific branch `ft-user-login-162949037` using 
```
git checkout ft-user-login-162949037
```

4. Run `npm install` to install all the modules listed in the `package.json` file.

5. Run `npm start` command to start the application.

6. The application should start successfully displaying a page as shown below.
screen shot 2019-02-14 at 12 24 37

7. On the navigation bar, click login. You will be routed to the login page as shown below:
screen shot 2019-02-12 at 19 02 56

8. Insert any random email and password in the fields provided.  You will receive relevant error messages as shown in the screenshots section.
To test a successful login, Use the following credentials. You will be redirected to the homepage when you successfully log in.
```
password: o.ogeto@yahoo.com
email: Ogeto1234$
```

9. To run tests, open the terminal and navigate to the project folder where you cloned the repository (as shown in the screenshot below) and run:
```
npm test
```
The following are sample screenshots of the anticipated outputs:
screen shot 2019-02-14 at 12 40 56
screen shot 2019-02-14 at 12 42 21

### What are the relevant pivotal tracker stories?

[#162949037](https://www.pivotaltracker.com/n/projects/2235171/stories/162949037)

#### 1. Error messages on submitting empty data
screen shot 2019-02-14 at 12 20 14

Empty password

screen shot 2019-02-14 at 12 20 49

#### 2. Error message on invalid credentials
screen shot 2019-02-14 at 12 21 22

### CODE REVIEW

**Review by Paulvitalis200 — COMMENTED** [review]
Hey @sharkdevs and @jomasim ,
I have managed to test this feature and it works as expected. Awesome UI I have also run the tests and all the checks were successful. I would however suggest the following:
1. The error message below should only be for registration not for login. When one put a password the login should only catch whether the password is correct or not.
image

**Review by Teatoller — CHANGES_REQUESTED** [review]
Hi,
1. At step ```7``` I suggest you include a payload or two of persons already registered to be used for step ```8```.
2. It would be better if the  page the user is directed to after login to be somehow different from what they began with.
e.g instead of the message 
>Welcome to Authors Haven
The place of choice.

You could have the message " You have logged in successfully"

3. Consider also changing the Navbar.
It is better at this stage not to have _**"Login", "Signup"**_ on the Navbar as you are already logged in. 
However, you could **have a Signout of Log out**.

4. The tests are running as expected and all passing

Regards
Steven Ennis

**Comment by sharkdevs** [comment]
> Hey @sharkdevs and @jomasim ,
> I have managed to test this feature and it works as expected. Awesome UI I have also run the tests and all the checks were successful. I would however suggest the following:
> 
> 1. The error message below should only be for registration not for login. When one put a password the login should only catch whether the password is correct or not.
>    image

I can see it paul,, However that is a backend issue we shall fix it in a bug PR later

**Comment by sharkdevs** [comment]
> Hi,
> 
> 1. At step `7` I suggest you include a payload or two of persons already registered to be used for step `8`.
> 2. It would be better if the  page the user is directed to after login to be somehow different from what they began with.
>    e.g instead of the message
> 
> > Welcome to Authors Haven
> > The place of choice.
> 
> You could have the message " You have logged in successfully"
> 
> 1. Consider also changing the Navbar.
>    It is better at this stage not to have _**"Login", "Signup"**_ on the Navbar as you are already logged in.
>    However, you could **have a Signout of Log out**.
> 2. The tests are running as expected and all passing
> 
> Regards
> Steven Ennis

Thank you, Steven, 
concerning redirection, we are redirecting to the homepage because: 
1. that is the main page that provides access to other resources after login.
2. For demonstration purposes, It would be good that a user does not stay on the same page.
As the application continues to grow, we shall have more options to handle this.

**Review by waracci — COMMENTED** [review]
Hey @sharkdevs and @jomasim I went through your front end and it works as expected but I noticed the error labels are showing both up and below the input boxes, my suggestion is that we could have one way of displaying the error labels; maybe above the input boxes so that we may have uniformity also on the Register page.

>On the register page we have the input boxes displaying above the input boxes

This is how your page looks like.
screenshot 2019-02-14 at 15 52 05

**Review by johnwayodi — COMMENTED** [review]
Tested and works as expected, just make the necessary changes as @waracci had mentioned to maintain uniformity.

**Review by Teatoller — APPROVED** [review]

**Comment by sharkdevs** [comment]
> Hey @sharkdevs and @jomasim I went through your front end and it works as expected but I noticed the error labels are showing both up and below the input boxes, my suggestion is that we could have one way of displaying the error labels; maybe above the input boxes so that we may have uniformity also on the Register page.
> 
> > On the register page we have the input boxes displaying above the input boxes
> 
> This is how your page looks like.
> screenshot 2019-02-14 at 15 52 05

@waracci @johnwayodi This issue is fixed. Thank you.

**Pull request merged**
