### PR TITLE
#162949028 Setup Authors Haven App

### PR DESCRIPTION
**Pull request by Teatoller**
#### What does this PR do?
This PR creates Authors Haven react application and set up the AirBnB's style guide.
#### Description of Task to be completed?
- [x] Create Authors Haven as a react application
- [x] Set up develop branch
- [x] Set up AirBnB as the Apps style guide
- [x] Set up .eslintrc file
#### How should this be manually tested?

1. Navigate to a folder where you would prefer to test the repository.

2. Create a directory
 ```$```  ```mkdir myproject```

3. Navigate to the directory "myproject"
 ```$```   ```cd myproject```
4. Clone the authors haven repository
  ```$```   ```git clone https://github.com/andela/ah-robotics-frontend.git```
5. Change the directory into the "ah-robotics-fronted"
  ```$```   ```cd ah-robotics-frontend```
6.  Checkout to the branch ch-project-setup-162949028
 ```$```   ```git checkout ch-project-setup-162949028```
7. Install dependancies from the package.json
 ```$```   ```npm install``` to install all the modules listed in the `package.json` file.

8. Start the application in development mode
  ```$```   ```npm start``` to runs the app in the development mode 

Opens http://localhost:3000 to view it in the browser.
 
#### What are the relevant pivotal tracker stories?
[#162949028](https://www.pivotaltracker.com/story/show/162949028)
#### Screenshots (if appropriate)

screenshot 2019-02-06 at 17 17 27

9. Stop the server on the terminal . Use command ```$``` ```control``` + ```c```

10. Test the AirBnb style guide lint. 
Use command on the terminal ```$``` ```npm run lint``` 
If any error is present it will be displayed on the terminal as  below;
screenshot 2019-02-06 at 19 28 41

#### Questions:

### CODE REVIEW

**Comment by jomasim** [comment]
@Teatoller Just add more description to your testing steps. For instance, you need to state what the `npm install` and `npm start` commands do in the testing process.

**Comment by Teatoller** [comment]
> @Teatoller Just add more description to your testing steps. For instance, you need to state what the `npm install` and `npm start` commands do in the testing process.

Hello @jomasim ,
I have incorporated the recommendations. You may review and verify the same.
Thank you.

**Review by waracci — COMMENTED** [review]
@Teatoller I tested it and it works, my PR is a testament that it works as expected.
👍

**Comment by waracci** [comment]
@Teatoller, kindly update your PT link to point to the specific story you worked on.

**Comment by Teatoller** [comment]
> @Teatoller I tested it and it works, my PR is a testament that it works as expected.
> 👍

Thank you

**Comment by Teatoller** [comment]
> @Teatoller, kindly update your PT link to point to the specific story you worked on.

Hey, you have made me learn how to refine this bit of my work. thank you.

**Review by Paulvitalis200 — COMMENTED** [review]
Hey @Teatoller ,
 Good work on setting up the project. Works as expected.

**Comment by sharkdevs** [comment]
Hello @Teatoller,
I have followed the steps to the end smoothly, It is working fine. Thank you.

**Comment by Teatoller** [comment]
> Hey @Teatoller ,
> Good work on setting up the project. Works as expected.

Thank @Paulstar200 for taking the time to review.
Regards
Steven Ennis

**Review by sharkdevs — COMMENTED** [review]
Hello @Teatoller,
I have followed the steps to the end smoothly, It is working fine. Thank you.

**Review by johnwayodi — COMMENTED** [review]
@Teatoller, nice work, I managed to follow your steps and set up the project.

**Comment by Teatoller** [comment]
> Hello @Teatoller,
> I have followed the steps to the end smoothly, It is working fine. Thank you.

Thank you @sharkdevs

**Comment by Teatoller** [comment]
> @Teatoller, nice work, I managed to follow your steps and set up the project.

Thank you @johnwayodi  for taking the time to test this chore.

Regards
Steven Ennis

**Pull request merged**
