### PR TITLE
#162949031 Travis Integration

### PR DESCRIPTION
**Pull request by Paulvitalis200**
#### What does this PR do?
Integrates Travis CI with the **ah-robotics-frontend** repository

#### Description of Task to be completed?
- [x] Link this repository with Travis CI
- [x] Add travis.yml file to project root directory

### How should this be manually tested?
1. Open the project repository on github [here](https://github.com/andela/ah-robotics-frontend/tree/develop)
2. Go to the **branch** section. By default, the branch should be on **develop**. Switch to the branch `ch-travis-integration-162949031`.
3. Scroll down to the Readme section.
4. Click on the build badge to see the build info on the travis-ci website.

#### Any background context you want to provide?
The build badge is currently `unknown` because the branch has not been merged to **develop**

#### What are the relevant pivotal tracker stories?
[162949031](https://www.pivotaltracker.com/n/projects/2235171/stories/162949031)

#### Screenshots (if appropriate)
Travis build status
image

Readme file
image

#### Questions:
Feel free to ask any queestions

### CODE REVIEW

**Review by waracci — COMMENTED** [review]
The badge seems not to display the build status, I have tried `hard-reloading` and clearing cache.

screenshot 2019-02-07 at 13 02 51

**Comment by waracci** [comment]
Or will it update when its merged to develop?

**Comment by Paulvitalis200** [comment]
> Or will it update when its merged to develop?

Yes. When it is merged to develop it will update. Currently, the badge points to develop. I have put that in the background section of the Pull Request. You can refer there.

**Comment by Teatoller** [comment]
Hi @Paulstar200 ,
>### How should this be manually tested?
1. Open the project repository on github [here](https://github.com/andela/ah-robotics-frontend/tree/develop)
2. Switch to the branch `ch-travis-integration-162949031`.

I am challenged, how does a user transition to step ```2``` from the step ```1```

Could you fill in the the missing steps to enable a user test this feature succesfully.

Thank you.

Regards
Steven Ennis

**Comment by Paulvitalis200** [comment]
> Hi @Paulstar200 ,
> 
> > ### How should this be manually tested?
> 
> 1. Open the project repository on github [here](https://github.com/andela/ah-robotics-frontend/tree/develop)
> 2. Switch to the branch `ch-travis-integration-162949031`.
> 
> I am challenged, how does a user transition to step `2` from the step `1`
> 
> Could you fill in the the missing steps to enable a user test this feature succesfully.
> 
> Thank you.
> 
> Regards
> Steven Ennis

Thank you for your feedback. I have edited the Pull Request with the step you have asked. You can go through it and try again.

**Review by sharkdevs — COMMENTED** [review]
In step 2, it would be preferable to add the command to switch to the new branch.

**Comment by Paulvitalis200** [comment]
> In step 2, it would be preferable to add the command to switch to the new branch.

Thank you for your feedback. I have updated it to suite this

**Review by johnwayodi — COMMENTED** [review]
Nice work, I clicked the badge and was able to see the build info on Travis-ci

**Pull request merged**
