### PR TITLE
#162949034 CircleCI and codeclimate test coverage 

### PR DESCRIPTION
**Pull request by Teatoller**
#### What does this PR do?
This PR sets up the circleCI and codeclimate coverage.
#### Description of Task to be completed?
- [x] Create .circleci folder
- [x] Create and add config.yml in .circleci folder
- [x] Set up node:8 in config.yml
- [x] Set up CC_TEST_REPORTER in config.yml
- [x] Set up test to run before and after build in config.yml
#### How should this be manually tested?

1. Navigate to a folder where you would prefer to test the repository.

2. Create a directory
 ```$```  ```mkdir myproject```

3. Navigate to the directory "myproject"
 ```$```   ```cd myproject```
4. Clone the authors haven repository
  ```$```   ```git clone https://github.com/andela/ah-robotics-frontend.git```
5. Change the directory into the "ah-robotics-fronted"
  ```$```   ```cd ah-robotics-frontend```
6.  Checkout to the branch ch-codeclimate-test-coverage-162949034
 ```$```   ```git checkout ch-codeclimate-test-coverage-162949034```
7. Install dependancies from the package.json
 ```$```   ```npm install``` to install all the modules listed in the `package.json` file.
8. To run test coverage on terminal run command
```npm test -- --coverage````
See screenshot image: 2
9. Click on README file and open in "PREVIEW" mode.
Screenshot image:1 circleCI and codeclimate badge integrated
screenshot 2019-02-07 at 13 19 11

#### Any background context you want to provide?
n/a
#### What are the relevant pivotal tracker stories?
[#162949034](https://www.pivotaltracker.com/story/show/162949034)
##### Image: 2 Test coverage on the terminal
screenshot 2019-02-07 at 13 11 14

#### Questions:

### CODE REVIEW

**Review by Paulvitalis200 — COMMENTED** [review]
Hey @Teatoller ,
 Good work on implementing the codeclimate test coverage. I have tested it and everything is working well.

**Review by sharkdevs — COMMENTED** [review]
Good work, Integration there.

**Comment by Teatoller** [comment]
> Hey @Teatoller ,
> Good work on implementing the codeclimate test coverage. I have tested it and everything is working well.

Thank you for reviewing this feature.
Regards
Steven Ennis

**Comment by Teatoller** [comment]
> Good work, Integration there.

Thank you for the review.

Regards
Steven Ennis

**Pull request merged**
